import { AppointmentStatus, CrmReminderStatus, CrmRuleType, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

type GenerateRemindersInput = {
  runAt?: Date;
};

type GenerateRemindersJobInput = {
  runAt?: Date;
  source: string;
  triggeredById?: string | null;
  triggeredByEmail?: string | null;
};

export type GenerateRemindersResult = {
  generatedPostService: number;
  generatedBirthday: number;
};

export type GenerateRemindersJobResult = GenerateRemindersResult & {
  runId: string;
};

type TemplateContext = {
  nome: string;
  servico?: string;
  barbeiro?: string;
  data?: string;
  barbearia: string;
  dias?: string;
};

function startOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function addDays(date: Date, days: number): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate() + days);
}

function toDateKey(date: Date): string {
  const y = date.getFullYear();
  const m = `${date.getMonth() + 1}`.padStart(2, "0");
  const d = `${date.getDate()}`.padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function toDateKeyInTimeZone(date: Date, timeZone: string): string {
  const formatter = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });

  return formatter.format(date);
}

function toMonthDayKeyInTimeZone(date: Date, timeZone: string): string {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(date);

  const month = parts.find((part) => part.type === "month")?.value;
  const day = parts.find((part) => part.type === "day")?.value;

  if (!month || !day) {
    throw new Error(`Unable to resolve month/day in timezone ${timeZone}`);
  }

  return `${month}-${day}`;
}

function resolveCrmTimeZone(): string {
  const configured = process.env.CRM_TIMEZONE?.trim();
  if (!configured) {
    return "America/Sao_Paulo";
  }

  try {
    new Intl.DateTimeFormat("en-US", { timeZone: configured }).format(new Date());
    return configured;
  } catch {
    return "America/Sao_Paulo";
  }
}

function formatDatePtBr(date: Date): string {
  return date.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" });
}

function hasContactPhone(phone: string): boolean {
  return phone.trim().length >= 8;
}

function serviceSummary(appointment: {
  service: { name: string };
  extraServices: Array<{ service: { name: string } }>;
}): string {
  const names = [appointment.service.name, ...appointment.extraServices.map((item) => item.service.name)];
  if (names.length <= 1) {
    return names[0] ?? "servico";
  }

  return `${names[0]} +${names.length - 1}`;
}

function renderTemplate(template: string, context: TemplateContext): string {
  return template
    .replaceAll("{nome}", context.nome)
    .replaceAll("{servico}", context.servico ?? "servico")
    .replaceAll("{barbeiro}", context.barbeiro ?? "barbeiro")
    .replaceAll("{data}", context.data ?? "")
    .replaceAll("{barbearia}", context.barbearia)
    .replaceAll("{dias}", context.dias ?? "");
}

async function createReminderIfNotExists(params: {
  dedupeKey: string;
  clientId: string;
  appointmentId?: string;
  type: CrmRuleType;
  scheduledFor: Date;
  messageSnapshot: string;
}) {
  try {
    const reminder = await prisma.crmReminder.create({
      data: {
        dedupeKey: params.dedupeKey,
        clientId: params.clientId,
        appointmentId: params.appointmentId,
        type: params.type,
        status: CrmReminderStatus.PENDING,
        scheduledFor: params.scheduledFor,
        messageSnapshot: params.messageSnapshot,
      },
      select: { id: true },
    });

    await prisma.crmReminderEvent.create({
      data: {
        reminderId: reminder.id,
        action: "GENERATED",
        details: "Generated by CRM daily job",
      },
    });

    return true;
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      return false;
    }

    throw error;
  }
}

export async function generateCrmReminders({ runAt = new Date() }: GenerateRemindersInput = {}): Promise<GenerateRemindersResult> {
  const [postServiceRule, birthdayRule] = await Promise.all([
    prisma.crmAutomationRule.upsert({
      where: { type: CrmRuleType.POST_SERVICE },
      update: {},
      create: {
        type: CrmRuleType.POST_SERVICE,
        enabled: true,
        daysAfterService: 14,
        template:
          "Oi {nome}, tudo bem? Ja faz {dias} dias do seu {servico} com {barbeiro}. Estamos a disposicao para manutencao na {barbearia}.",
      },
    }),
    prisma.crmAutomationRule.upsert({
      where: { type: CrmRuleType.BIRTHDAY },
      update: {},
      create: {
        type: CrmRuleType.BIRTHDAY,
        enabled: true,
        daysAfterService: null,
        template:
          "Feliz aniversario, {nome}! A equipe da {barbearia} te deseja um dia incrivel. Conte com a gente para seu proximo atendimento.",
      },
    }),
  ]);

  const barbershopName = process.env.BARBERSHOP_NAME?.trim() || "Barbearia";
  const crmTimeZone = resolveCrmTimeZone();
  let generatedPostService = 0;
  let generatedBirthday = 0;

  const runDayStart = startOfDay(runAt);
  const runDateKey = toDateKey(runDayStart);
  const runBirthdayDateKey = toDateKeyInTimeZone(runAt, crmTimeZone);
  const runBirthdayMonthDay = toMonthDayKeyInTimeZone(runAt, crmTimeZone);

  if (postServiceRule?.enabled) {
    const daysAfter = postServiceRule.daysAfterService ?? 14;
    const targetDay = addDays(runDayStart, -daysAfter);
    const targetDayEnd = addDays(targetDay, 1);

    const appointments = await prisma.appointment.findMany({
      where: {
        status: AppointmentStatus.FINALIZADO,
        startsAt: { gte: targetDay, lt: targetDayEnd },
      },
      include: {
        client: { select: { id: true, name: true, phone: true } },
        barber: { select: { name: true } },
        service: { select: { name: true } },
        extraServices: { include: { service: { select: { name: true } } } },
      },
    });

    for (const appointment of appointments) {
      if (!hasContactPhone(appointment.client.phone)) {
        continue;
      }

      const messageSnapshot = renderTemplate(postServiceRule.template, {
        nome: appointment.client.name,
        servico: serviceSummary(appointment),
        barbeiro: appointment.barber.name,
        data: formatDatePtBr(appointment.startsAt),
        dias: `${daysAfter}`,
        barbearia: barbershopName,
      });

      const created = await createReminderIfNotExists({
        dedupeKey: `POST_SERVICE:${appointment.id}:${runDateKey}`,
        clientId: appointment.client.id,
        appointmentId: appointment.id,
        type: CrmRuleType.POST_SERVICE,
        scheduledFor: runAt,
        messageSnapshot,
      });

      if (created) {
        generatedPostService += 1;
      }
    }
  }

  if (birthdayRule?.enabled) {
    const allClients = await prisma.client.findMany({
      select: {
        id: true,
        name: true,
        phone: true,
        birthDate: true,
      },
    });

    for (const client of allClients) {
      if (!hasContactPhone(client.phone)) {
        continue;
      }

      const clientBirthMonthDay = toMonthDayKeyInTimeZone(client.birthDate, crmTimeZone);

      if (clientBirthMonthDay !== runBirthdayMonthDay) {
        continue;
      }

      const messageSnapshot = renderTemplate(birthdayRule.template, {
        nome: client.name,
        data: formatDatePtBr(runAt),
        barbearia: barbershopName,
      });

      const created = await createReminderIfNotExists({
        dedupeKey: `BIRTHDAY:${client.id}:${runBirthdayDateKey}`,
        clientId: client.id,
        type: CrmRuleType.BIRTHDAY,
        scheduledFor: runAt,
        messageSnapshot,
      });

      if (created) {
        generatedBirthday += 1;
      }
    }
  }

  return {
    generatedPostService,
    generatedBirthday,
  };
}

export async function generateCrmRemindersWithJobRun({
  runAt = new Date(),
  source,
  triggeredById = null,
  triggeredByEmail = null,
}: GenerateRemindersJobInput): Promise<GenerateRemindersJobResult> {
  const run = await prisma.crmJobRun.create({
    data: {
      source,
      triggeredById,
      triggeredByEmail,
      startedAt: new Date(),
    },
    select: { id: true },
  });

  try {
    const result = await generateCrmReminders({ runAt });

    await prisma.crmJobRun.update({
      where: { id: run.id },
      data: {
        success: true,
        generatedPostService: result.generatedPostService,
        generatedBirthday: result.generatedBirthday,
        finishedAt: new Date(),
      },
    });

    return {
      runId: run.id,
      generatedPostService: result.generatedPostService,
      generatedBirthday: result.generatedBirthday,
    };
  } catch (error) {
    await prisma.crmJobRun.update({
      where: { id: run.id },
      data: {
        success: false,
        errorMessage: error instanceof Error ? error.message : "Unknown error",
        finishedAt: new Date(),
      },
    });

    throw error;
  }
}
